name: Build CrushFTP DMZ Docker Image

on:
  push:
    branches:
      - main
      
env:
  TAG: crushftp10.8.5.12.java.17

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clone repository into the GitHub Actions runner (Checkout repo) 
        uses: actions/checkout@v4

      - name: Download CrushFTP10.zip with retry and validation from crushftp.com
        run: |
          set -euo pipefail
          wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 -O CrushFTP10.zip https://www.crushftp.com/early10/CrushFTP10.zip
          echo "Validating CrushFTP10.zip integrity..."
          unzip -t CrushFTP10.zip
      
      - name: Preparing clean build directory
        run: |
          rm -rf build/
          mkdir -p build/
      
      - name: Unzip CrushFTP10.zip and cleanup zip file
        run: unzip -o -q CrushFTP10.zip -d build/

      - name: Docker Login
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin

      - name: Build Docker image
        run: sudo docker build -t localhost:5000/crushftp:$TAG .

      - name: Push Docker image
        run: sudo docker push localhost:5000/crushftp:$TAG
