name: Build CrushFTP DMZ Docker Image

on:
  push:
    branches:
      - main

env:
  TAG: crushftp10.8.5.12.java.21
  IMAGE_NAME: crushftpdmz

jobs:
  build:
    runs-on: self-hosted

    permissions:
      packages: write
      contents: read

    steps:
      - name: Clone repository into the GitHub Actions runner 
        uses: actions/checkout@v4

      - name: Download CrushFTP10.zip with retry and validation from crushftp.com
        run: |
          set -euo pipefail
          wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 -O CrushFTP10.zip https://www.crushftp.com/early10/CrushFTP10.zip
          echo "Validating CrushFTP10.zip integrity..."
          unzip -t CrushFTP10.zip

      - name: Preparing clean build directory
        run: |
          rm -rf build/
          mkdir -p build/

      - name: Unzip CrushFTP build and cleanup zip file
        run: unzip -o -q CrushFTP10.zip -d build/

      - name: Get JFrog Access Token
        id: get_token
        run: |
          response=$(curl -su "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_APIKEY }}" \
            -X POST "https://artifactory.server01.com/artifactory/api/security/token" \
            -d "username=${{ secrets.JFROG_USERNAME }}" \
            -d "expires_in=3600")
          echo "$response"
          token=$(echo "$response" | jq -r '.access_token')
          echo "token=$token" >> "$GITHUB_OUTPUT"

      - name: Login to Artifactory Docker Registry
        run: echo "${{ steps.get_token.outputs.token }}" | docker login artifactory.server01.com -u "${{ secrets.JFROG_USERNAME }}" --password-stdin
      
      - name: Build Podman image
        run: docker build -t artifactory.server01.com/docker-aucrushftpdmz-local/$IMAGE_NAME:$TAG .

      - name: Push Podman image
        run: docker push artifactory.server01.com/docker-aucrushftpdmz-local/$IMAGE_NAME:$TAG
